// examples/react/src/components/QtyInput.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { useProduct, getProductLimits, snapQuantity } from "@spaceis/react";

interface QtyInputProps {
  value: number;
  slug: string;
  onSet: (qty: number) => void;
}

export function QtyInput({ value, slug, onSet }: QtyInputProps) {
  const { data: product } = useProduct(slug);
  const limits = product ? getProductLimits(product) : { min: 1, max: 99, step: 1 };

  const [inputVal, setInputVal] = useState(String(value));

  useEffect(() => {
    setInputVal(String(value));
  }, [value]);

  const commit = useCallback(() => {
    let n = parseInt(inputVal, 10);
    if (isNaN(n)) n = value;
    n = snapQuantity(n, limits);
    setInputVal(String(n));
    if (n !== value) {
      onSet(n);
    }
  }, [inputVal, value, limits, onSet]);

  return (
    <input
      className="qty-input"
      type="text"
      inputMode="numeric"
      value={inputVal}
      onChange={(e) => setInputVal(e.target.value)}
      onBlur={commit}
      onKeyDown={(e) => { if (e.key === "Enter") e.currentTarget.blur(); }}
    />
  );
}

// examples/vue/components/QtyInput.vue
<script setup lang="ts">
import { useProduct, getProductLimits, snapQuantity } from '@spaceis/vue';

const props = defineProps<{
  value: number;
  slug: string;
  onSet: (qty: number) => void;
}>();

const slugRef = computed(() => props.slug); const { data: product } = useProduct(slugRef);

const limits = computed(() =>
  product.value ? getProductLimits(product.value) : { min: 1, max: 99, step: 1 },
);

const inputVal = ref(String(props.value));

watch(
  () => props.value,
  (v) => {
    inputVal.value = String(v);
  },
);

function commit() {
  // Don't commit until product limits are loaded
  if (!product.value) {
    inputVal.value = String(props.value);
    return;
  }
  let n = parseInt(inputVal.value, 10);
  if (isNaN(n)) n = props.value;
  n = snapQuantity(n, limits.value);
  inputVal.value = String(n);
  if (n !== props.value) {
    props.onSet(n);
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter') (e.target as HTMLInputElement).blur();
}
</script>

<template>
  <input
    class="qty-input"
    type="text"
    inputmode="numeric"
    :value="inputVal"
    @input="inputVal = ($event.target as HTMLInputElement).value"
    @blur="commit"
    @keydown="handleKeydown"
  />
</template>
