// examples/vue/components/cart/DiscountSection.vue
<script setup lang="ts">
import { useCart } from '@spaceis/vue';
import { getErrorMessage } from '~/utils/helpers';

const { hasDiscount, discount, applyDiscount, removeDiscount } = useCart();
const { success: toastSuccess, error: toastError } = useToast();

const code = ref('');
const pending = ref(false);

async function apply() {
  const trimmed = code.value.trim();
  if (!trimmed || pending.value) return;
  pending.value = true;
  try {
    await applyDiscount(trimmed);
    toastSuccess('Discount applied!');
    code.value = '';
  } catch (err) {
    toastError(getErrorMessage(err) || 'Invalid code');
  } finally {
    pending.value = false;
  }
}

async function remove() {
  if (pending.value) return;
  pending.value = true;
  try {
    await removeDiscount();
  } catch (err) {
    toastError(getErrorMessage(err));
  } finally {
    pending.value = false;
  }
}
</script>

<template>
  <div v-if="hasDiscount && discount" class="discount-active">
    <span>
      Code: <strong>{{ discount.code }}</strong>
    </span>
    <span class="discount-active-pct">-{{ discount.percentage_discount }}%</span>
    <button class="discount-remove" :disabled="pending" @click="remove">Remove</button>
  </div>
  <div v-else class="discount-row">
    <input
      v-model="code"
      type="text"
      placeholder="Discount code"
      autocomplete="off"
      maxlength="64"
      @keydown.enter="apply"
    />
    <button class="discount-apply" :disabled="pending" @click="apply">
      {{ pending ? '...' : 'Apply' }}
    </button>
  </div>
</template>

// examples/react/src/features/cart/DiscountSection.tsx
"use client";

import { useState } from "react";
import { useCart } from "@spaceis/react";
import { toast } from "sonner";
import { getErrorMessage } from "@/lib/helpers";

/**
 * Apply / remove cart discount. Used by CartDrawer, CartPage and CheckoutPage —
 * reads cart state + actions from `useCart()` directly so callers need no props.
 */
export function DiscountSection() {
  const { hasDiscount, discount, applyDiscount, removeDiscount } = useCart();
  const [code, setCode] = useState("");
  const [pending, setPending] = useState(false);

  const apply = async () => {
    const trimmed = code.trim();
    if (!trimmed || pending) return;
    setPending(true);
    try {
      await applyDiscount(trimmed);
      toast.success("Discount applied!");
      setCode("");
    } catch (err) {
      toast.error(getErrorMessage(err) || "Invalid code");
    } finally {
      setPending(false);
    }
  };

  const remove = async () => {
    if (pending) return;
    setPending(true);
    try {
      await removeDiscount();
    } catch (err) {
      toast.error(getErrorMessage(err));
    } finally {
      setPending(false);
    }
  };

  if (hasDiscount && discount) {
    return (
      <div className="discount-active">
        <span>
          Code: <strong>{discount.code}</strong>
        </span>
        <span className="discount-active-pct">
          -{discount.percentage_discount}%
        </span>
        <button
          className="discount-remove"
          onClick={remove}
          disabled={pending}
        >
          Remove
        </button>
      </div>
    );
  }

  return (
    <div className="discount-row">
      <input
        type="text"
        placeholder="Discount code"
        value={code}
        onChange={(e) => setCode(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") apply();
        }}
        autoComplete="off"
        maxLength={64}
      />
      <button className="discount-apply" onClick={apply} disabled={pending}>
        {pending ? "..." : "Apply"}
      </button>
    </div>
  );
}
