// examples/vue/components/ProductCard.vue
<script setup lang="ts">
import type { IndexShopProduct } from '@spaceis/vue';
import { fp } from '~/utils/helpers';

const props = defineProps<{
  product: IndexShopProduct;
  index: number;
}>();

const priceField = computed(() => props.product.minimal_price);
</script>

<template>
  <NuxtLink
    :to="`/product/${product.slug}`"
    class="product-card"
    :style="{ animationDelay: `${index * 0.04}s`, textDecoration: 'none' }"
  >
    <div class="product-img-wrap">
      <img
        v-if="product.image"
        class="product-img"
        :src="product.image"
        :alt="product.name"
        loading="lazy"
      />
      <div v-else class="product-img-placeholder">
        <PlaceholderSvg :size="32" />
      </div>
      <div v-if="product.percentage_discount" class="product-discount-badge">
        -{{ product.percentage_discount }}%
      </div>
    </div>
    <div class="product-body">
      <div class="product-name">{{ product.name }}</div>
      <div class="product-footer">
        <div>
          <span class="product-price">{{ fp(priceField) }}</span>
        </div>
        <span class="view-btn">View</span>
      </div>
    </div>
  </NuxtLink>
</template>

// examples/react/src/features/products/ProductCard.tsx
import Link from "next/link";
import type { IndexShopProduct } from "@spaceis/react";
import { fp, PlaceholderSVG } from "@/lib/helpers";

interface ProductCardProps {
  product: IndexShopProduct;
  index: number;
}

export function ProductCard({ product, index }: ProductCardProps) {
  const priceField = product.minimal_price;

  return (
    <Link
      href={`/product/${product.slug}`}
      className="product-card"
      style={{ animationDelay: `${index * 0.04}s`, textDecoration: "none" }}
    >
      <div className="product-img-wrap">
        {product.image ? (
          <img
            className="product-img"
            src={product.image}
            alt={product.name}
            loading="lazy"
          />
        ) : (
          <div className="product-img-placeholder">
            <PlaceholderSVG size={32} />
          </div>
        )}
        {product.percentage_discount ? (
          <div className="product-discount-badge">
            -{product.percentage_discount}%
          </div>
        ) : null}
      </div>
      <div className="product-body">
        <div className="product-name">{product.name}</div>
        <div className="product-footer">
          <div>
            <span className="product-price">{fp(priceField)}</span>
          </div>
          <span className="view-btn">View</span>
        </div>
      </div>
    </Link>
  );
}

/** Skeleton grid for loading states */
export function ProductGridSkeleton({ count = 8 }: { count?: number }) {
  return (
    <div className="products-grid">
      {Array.from({ length: count }).map((_, i) => (
        <div key={i} className="skeleton-card">
          <div className="skeleton skeleton-img" />
          <div className="skeleton-body">
            <div className="skeleton skeleton-line" />
            <div className="skeleton skeleton-line short" />
            <div className="skeleton skeleton-line price" />
          </div>
        </div>
      ))}
    </div>
  );
}
