// examples/vue/components/products/Recommendations.vue
<script setup lang="ts">
import { useProductRecommendations, useCart, fromApiQty, type PackageRecommendation } from '@spaceis/vue';
import { fp, getErrorMessage } from '~/utils/helpers';

const props = withDefaults(
  defineProps<{
    slug: string | null;
    title?: string;
  }>(),
  { title: 'Recommended' },
);

const slugRef = computed(() => props.slug);
const { data: recs } = useProductRecommendations(slugRef);
const { add } = useCart();
const { success: toastSuccess, error: toastError } = useToast();

const addingMap = reactive<Record<string, boolean>>({});
const addedMap = reactive<Record<string, boolean>>({});

async function handleAdd(rec: PackageRecommendation) {
  const variantUuid = rec.variant?.uuid;
  if (!variantUuid || addingMap[variantUuid]) return;

  const minQty = rec.shop_product?.min_quantity ? fromApiQty(rec.shop_product.min_quantity) : 1;

  addingMap[variantUuid] = true;
  try {
    await add(variantUuid, minQty);
    toastSuccess('Added to cart!');
    addedMap[variantUuid] = true;
    setTimeout(() => { addedMap[variantUuid] = false; }, 1500);
  } catch (err) {
    toastError(getErrorMessage(err));
  } finally {
    addingMap[variantUuid] = false;
  }
}
</script>

<template>
  <div v-if="recs && recs.length > 0" class="recs-section">
    <div class="recs-section-title">{{ title }}</div>
    <div class="recs-grid">
      <div
        v-for="rec in recs"
        :key="rec.variant?.uuid ?? rec.name"
        class="rec-card"
      >
        <img
          v-if="rec.variant?.image || rec.shop_product?.image"
          class="rec-img"
          :src="rec.variant?.image || rec.shop_product?.image"
          alt=""
        />
        <div v-else class="rec-img-placeholder">
          <PlaceholderSvg :size="16" />
        </div>
        <div class="rec-info">
          <div class="rec-name">{{ rec.name || rec.shop_product?.name || '' }}</div>
          <div class="rec-price-row">
            <span class="rec-price">
              {{ fp(rec.price * (rec.shop_product?.min_quantity ? fromApiQty(rec.shop_product.min_quantity) : 1)) }}
            </span>
            <span v-if="rec.base_price !== rec.price" class="rec-old-price">
              {{ fp(rec.base_price * (rec.shop_product?.min_quantity ? fromApiQty(rec.shop_product.min_quantity) : 1)) }}
            </span>
            <span
              v-if="(rec.shop_product?.min_quantity ? fromApiQty(rec.shop_product.min_quantity) : 1) > 1"
              class="rec-qty-label"
            >
              ({{ rec.shop_product?.min_quantity ? fromApiQty(rec.shop_product.min_quantity) : 1 }} szt)
            </span>
          </div>
        </div>
        <button
          class="rec-add-btn"
          :disabled="addingMap[rec.variant?.uuid] || !rec.variant?.uuid"
          title="Add to cart"
          aria-label="Add to cart"
          @click="handleAdd(rec)"
        >
          {{ addingMap[rec.variant?.uuid] ? '...' : addedMap[rec.variant?.uuid] ? '\u2713' : '+' }}
        </button>
      </div>
    </div>
  </div>
</template>

// examples/react/src/features/products/Recommendations.tsx
"use client";

import { useState } from "react";
import { useProductRecommendations, useCart, fromApiQty, type PackageRecommendation } from "@spaceis/react";
import type { CartMutationResponse } from "@spaceis/sdk";
import { fp, PlaceholderSVG, getErrorMessage } from "@/lib/helpers";
import { toast } from "sonner";

interface RecommendationsProps {
  slug: string | null;
  title?: string;
}

export function Recommendations({ slug, title = "Recommended" }: RecommendationsProps) {
  const { data: recs } = useProductRecommendations(slug);
  const { add } = useCart();

  if (!recs || recs.length === 0) return null;

  return (
    <div className="recs-section">
      <div className="recs-section-title">{title}</div>
      <div className="recs-grid">
        {recs.map((rec: PackageRecommendation) => (
          <RecCard key={rec.variant?.uuid ?? rec.shop_product.uuid} rec={rec} onAdd={add} />
        ))}
      </div>
    </div>
  );
}

function RecCard({ rec, onAdd }: { rec: PackageRecommendation; onAdd: (uuid: string, qty?: number) => Promise<CartMutationResponse> }) {
  const [adding, setAdding] = useState(false);
  const [added, setAdded] = useState(false);

  const minQty = rec.shop_product?.min_quantity
    ? fromApiQty(rec.shop_product.min_quantity)
    : 1;

  const imgSrc = rec.variant?.image || rec.shop_product?.image || null;
  const name = rec.name || rec.shop_product?.name || "";
  const variantUuid = rec.variant?.uuid;
  const hasDiscount = rec.base_price !== rec.price;

  const handleAdd = async () => {
    if (!variantUuid || adding) return;
    setAdding(true);
    try {
      await onAdd(variantUuid, minQty);
      toast.success("Added to cart!");
      setAdded(true);
      setTimeout(() => { setAdded(false); }, 1500);
    } catch (err) {
      toast.error(getErrorMessage(err));
    } finally {
      setAdding(false);
    }
  };

  return (
    <div className="rec-card">
      {imgSrc ? (
        <img className="rec-img" src={imgSrc} alt="" />
      ) : (
        <div className="rec-img-placeholder">
          <PlaceholderSVG size={16} />
        </div>
      )}
      <div className="rec-info">
        <div className="rec-name">{name}</div>
        <div className="rec-price-row">
          <span className="rec-price">{fp(rec.price * minQty)}</span>
          {hasDiscount && (
            <span className="rec-old-price">{fp(rec.base_price * minQty)}</span>
          )}
          {minQty > 1 && (
            <span className="rec-qty-label">({minQty} szt)</span>
          )}
        </div>
      </div>
      <button
        className="rec-add-btn"
        disabled={adding || !variantUuid}
        onClick={handleAdd}
        title="Add to cart"
        aria-label="Add to cart"
      >
        {adding ? "..." : added ? "\u2713" : "+"}
      </button>
    </div>
  );
}
